### ISSUE TITLE
tensorflow InvalidArgumentError

### ISSUE THREAD

**Issue by bladejun** [SIAnalytics/simplified_rbox_cnn#3]
InvalidArgumentError (see above for traceback): indices[199,299,0] = [199, 299, -1] does not index into param shape [300,300,24]
         [[node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/NonMaxSuppressionRbox/IOURbox/cond/IntersectionRboxTF_1/cond/GatherNd
_2 (defined at /root/dacon_image/simplified_rbox_cnn/core/rbox_list_ops.py:381) ]]

train.py를 실행시키는 도중에 발생한 에러인데 tensor의 shape형태가 안맞는건지 이런 에러 보신적 있으시면 조언 한 번 해주시면 감사하겠습니다

**Comment by Ilevk** [comment]
개발 환경은 tf1.6 cuda 9.0 으로 맞추셨나요?
저는 tensorflow 1.6 공식 도커 이미지로 학습하는데 이런 에러는 발생하지 않았습니다.

**Comment by bladejun** [comment]
test용으로 tensorflow cpu에 1.6버젼으로 진행했습니다
혹시 제가 20장만으로 학습을 시킨것도 문제가 될까요?

**Comment by jamesKoo** [comment]
intersection_tf 함수 구현자체가 GPU 버전에서만 테스트되었고 CPU버전에서는 제대로 작동하지 않습니다. 
아마도 tensorflow의 cpu버전과 gpu버전의 행렬 처리 부분이 미묘하게 달라서 그런것 같습니다.

rbox_list_ops.py의 intersection함수의 'ver' 파라미터를 'opencv' 또는 'shapely'로 변경하면 cpu 버전에서 정상적으로 돌아갈 겁니다.

20장만으로 학습을 시킨건 전혀 문제가 되지 않습니다.

**Comment by bladejun** [comment]
답변해주셔서 정말 감사합니다
한 번 시도해보겠습니다
바쁜 와중에 친절하게 답변해주셔서 정말 감사합니다
-----Original Message-----
