### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by bladejun** [SIAnalytics/simplified_rbox_cnn#4]
현재 GeForce RTX 2080 4대 1대당 8기가 정도 되는데

2020-02-10 13:01:25.447825: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.14GiB.

The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

2.14GiB도 할당을 못하는데 이건 메모리 문제가 맞는건가요?

**Comment by jamesKoo** [comment]
8GB를 다 사용한 상태에서 추가로 2.14GB를 할당하지 못한 에러로 최소 요구되는 12GB입니다. 
8GB에서 실행하려고 하면 입력 이미지를 768보다 더 줄이거나 Anchor의 종류를 줄여서 하면 됩니다.
