### ISSUE TITLE
Tensorflow version problem

### ISSUE THREAD

**Issue by HyunjiEllenPak** [SIAnalytics/simplified_rbox_cnn#5]
안녕하세요. 코드를 실행해보려다가 문제가 생겨서 질문드립니다.
Tensorflow1.6을 사용하라고 제시되어있는데, 제가 사용하는 GPU가 CUDA9.0이랑 호환이 되지 않기에 어쩔수없이 cuda10.0, tensorflow>=1.13.1을 설치하였습니다.  그런데 TF1.13.1를 설치한 후 tfrecords을 준비하고 train.py를 실행시켜보니 CUDA에러가 나면서 코드가 실행이 되지 않습니다.  이와 같이 TF1.6을 사용할 수 없는 PC에서는 이 코드를 실행해볼 수 없는 건가요? 다른 TF버전으로 가능한 방법이 있으면 알려주시면 감사하겠습니다.

- GPU: RTX 2080 SUPER

**Comment by HyunjiEllenPak** [comment]
버전 문제는 해결했습니다. 
현재 failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED에러가 발생하는데, 이 코드가 RTX2080 SUPER 8G 하나로 실행하기 무리인가요?

**Comment by jamesKoo** [comment]
저 에러 메시지만으로 정확한 에러는 모르겠지만, 기본 설정에서 최소 요구되는 GPU 메모리는 12GB입니다. 
8GB에서 실행하려고 하면 입력 이미지를 768보다 더 줄이거나 Anchor의 종류를 줄여서 하면 됩니다.
